site_name: valid8
# site_description: 'A short description of my project'
repo_url: https://github.com/smarie/python-valid8
pages:
    - Home: index.md
    - Why validation: why_validation.md
    - Usage details: usage.md
    - Built-in validation functions: base_validation_lib.md
    - Other validation libs: other_libs.md
    - Changelog: changelog.md
theme: material  # readthedocs  mkdocs

markdown_extensions:
  - admonition  # to add notes such as http://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite(guess_lang=false)
  - toc(permalink=true)