site_name: valid8
# site_description: 'A short description of my project'
repo_url: https://github.com/smarie/python-valid8
pages:
    - Home and usage: index.md
    - Why validation: why_validation.md
    #- Usage details: usage.md
    - For `valid8` decorators only:
      - Accepted base validation functions: decorators/accepted.md
      - Built-in base validation functions: decorators/base_validation_lib.md
      - Composing base validation functions: decorators/composition.md
    - valid8 + other tools: valid8_with_other.md
    - Examples/Recipes:
      - Overview: examples/overview.md
      - Example 1: examples/example1.md
      - Example 2: examples/example2.md
      - Example 3: examples/example3.md
      #- Example 4: examples/example4.md
      #- Example 5: examples/example5.md
    - Other validation libs: other_libs.md
    - Changelog: changelog.md
theme: material  # readthedocs  mkdocs

markdown_extensions:
  - admonition  # to add notes such as http://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite(guess_lang=false)
  - toc(permalink=true)